Algoritmo "Enquanto"
Var
    Nomes: Vetor[0..4] De Caractere
    I: Inteiro

Inicio
    Nomes[0] <- "Joao"
    Nomes[1] <- "Maria"
    Nomes[2] <- "Jose"
    Nomes[3] <- "Ana"
    Nomes[4] <- "Jorge"
    
//    Escreval(Nomes[0])
//    Escreval(Nomes[1])
//    Escreval(Nomes[2])
//    Escreval(Nomes[3])
//    Escreval(Nomes[4])
    
    I <- 0
    Enquanto I < 5 Faca
       Escreval (Nomes[I])
       I <- I + 1
    FimEnquanto

Fimalgoritmo