Algoritmo "MédiadeNotas"

Var
    NotaA, NotaB, NotaC, NotaD, Media: Real

Inicio
      Escreva ("Informe a primeira nota: ")
      Leia (NotaA)
      
      Escreva ("Informe a segunda nota: ")
      Leia (NotaB)
      
      Escreva ("Informe a terceira nota: ")
      Leia (NotaC)
      
      Escreva ("Inoforme a quarta nota: ")
      Leia (NotaD)
      
      Media <- (NotaA + NotaB + NotaC + NotaD) / 4
      Escreva ("A média de notas é: ", Media)

Fimalgoritmo